### ISSUE TITLE
ExanteSymbolType for Crypto

### ISSUE THREAD

**Issue by alexander-myltsev** [d-ugarov/Exante.Net#1]
Hi! Thanks for the lib.

I know Exante has Crypto from their web interface. Do you know if there is a symbol type for that?

**Comment by d-ugarov** [comment]
Symbol type in Exante for Crypto: FUND

**Comment by alexander-myltsev** [comment]
That's a weird name. Do you think if they can create a new fund that is not related to Crypto?

**Comment by d-ugarov** [comment]
Their api is not the most convenient and sometimes their servers doesn't work stably.
I think they can do anything.
