### ISSUE TITLE
Library robustness against load stress

### ISSUE THREAD

**Issue by alexander-myltsev** [d-ugarov/Exante.Net#3]
Hi,

If I subscribe for 100 symbols with steaming API, would the Exante.Net survive?

If the internet connection is lost for, say, 5 minutes would it survive? 

How would it do exactly? By long timeout? By resubscribing to symbols? By somehow else?

**Comment by alexander-myltsev** [comment]
@d-ugarov Dmitry? ⬆️

**Comment by d-ugarov** [comment]
For Exante.Net doesn't matter how many symbols was subscribed. It read from stream per line and parse data. Only Exante can set any limit (from docs: URL should not be longer than 2000 symbols).

Exante 'streams' looks like SSE. Client send GET request and read data from response stream.
If connection lost at reading data, library try to connect and subscribe again.
