### ISSUE TITLE
Exante.Net lib fails to connect to Exante API in Release mode

### ISSUE THREAD

**Issue by alexander-myltsev** [d-ugarov/Exante.Net#4]
Hi Dmitry @d-ugarov,

Please, take a look at https://github.com/QuantConnect/Lean.Brokerages.Exante/commit/7ae9ddc831cc9d3b3ae86d4398f5d5e2d209e7a6#diff-c53ea2b2ff0fb4ec9c3eb0a18487d77e2f46e16887f9c71eade998e5b9c3c298 . Exactly same code passes tests related to Exante in Debug mode, but fails in Release. As an author of the lib, do you have an idea why might be the cause?

**Comment by d-ugarov** [comment]
Exante.Net doesn't have different logic for the DEBUG/RELEASE configuration and works the same in both configurations.
There may be a problem in configuration in the project that uses lib.
